### PR TITLE
Use git clone --recursive in build instructions

### PR DESCRIPTION
**Pull request by estan**

### CODE REVIEW

**Comment by steveire** [comment]
This isn't needed for me to build I think. Do any of the repos have git submodules themselves? Which?

**Comment by estan** [comment]
Ah. Hm, if I do just `git clone git@github.com:steveire/frameworks-bindings.git`, the submodule directories are all empty initially. They aren't for you? Maybe there's a difference in behavior in different Git versions?

**Comment by steveire** [comment]
Ah, sorry. I misunderstood. There was a 

```
git submodules update --init 
```

line there in my head :).

**Comment by estan** [comment]
But of course :)

**Pull request merged**
