### PR TITLE
Specify CMAKE_{MODULE|PREFIX}_PATH

### PR DESCRIPTION
**Pull request by estan**
This was required for me or the new Python stuff in ECM wasn't found.

### CODE REVIEW

**Comment by steveire** [comment]
This doesn't make sense. Please do this:

```
frameworks-bindings{master}$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index c0b9fde..12a78fb 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -26,14 +26,14 @@ endmacro()
add_repo(extra-cmake-modules DEPENDS "")

add_repo(kitemmodels DEPENDS extra-cmake-modules)
-add_repo(kcoreaddons DEPENDS extra-cmake-modules)
-add_repo(kdbusaddons DEPENDS extra-cmake-modules)
-add_repo(kguiaddons DEPENDS extra-cmake-modules)
-add_repo(kwidgetsaddons DEPENDS extra-cmake-modules)
-add_repo(kjobwidgets DEPENDS kcoreaddons kwidgetsaddons)
-add_repo(kconfig DEPENDS extra-cmake-modules)
-add_repo(kcompletion DEPENDS kconfig kwidgetsaddons)
-add_repo(kauth DEPENDS kcoreaddons)
-add_repo(kcodecs DEPENDS extra-cmake-modules)
-add_repo(ki18n DEPENDS extra-cmake-modules)
-add_repo(kconfigwidgets DEPENDS kcodecs kwidgetsaddons kconfig kauth)
+# add_repo(kcoreaddons DEPENDS extra-cmake-modules)
+# add_repo(kdbusaddons DEPENDS extra-cmake-modules)
+# add_repo(kguiaddons DEPENDS extra-cmake-modules)
+# add_repo(kwidgetsaddons DEPENDS extra-cmake-modules)
+# add_repo(kjobwidgets DEPENDS kcoreaddons kwidgetsaddons)
+# add_repo(kconfig DEPENDS extra-cmake-modules)
+# add_repo(kcompletion DEPENDS kconfig kwidgetsaddons)
+# add_repo(kauth DEPENDS kcoreaddons)
+# add_repo(kcodecs DEPENDS extra-cmake-modules)
+# add_repo(ki18n DEPENDS extra-cmake-modules)
+# add_repo(kconfigwidgets DEPENDS kcodecs kwidgetsaddons kconfig kauth)
```

and then this:

```
kitemmodels{master}$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1d120c8..10e97ae 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -4,13 +4,15 @@ project(KItemModels)

include(FeatureSummary)
find_package(ECM 5.22.0  NO_MODULE)
+message("ECM : ${ECM_DIR}")
set_package_properties(ECM PROPERTIES TYPE REQUIRED DESCRIPTION "Extra CMake Modules." URL "https://projects.kde.org/projects/kdesupport/extra-cmake-modules")
feature_summary(WHAT REQUIRED_PACKAGES_NOT_FOUND FATAL_ON_MISSING_REQUIRED_PACKAGES)


set(CMAKE_MODULE_PATH ${ECM_MODULE_PATH} ${ECM_KDE_MODULE_DIR})

-include(KDEInstallDirs)
+include(KDEInstallDirs RESULT_VARIABLE dir)
+message("DIR: ${dir}")
include(KDEFrameworkCompilerSettings NO_POLICY_SCOPE)
include(KDECMakeSettings)
```

or similar, and say what exactly can't be found as it is.

**Comment by estan** [comment]
I'm sorry for the terse description, I shouldn't have filed this in such a hurry.

I patched as you suggested, and during the `cmake --build .` step I get:

```
ECM : /usr/share/ECM/cmake
DIR: /usr/share/ECM/kde-modules/KDEInstallDirs.cmake
```

and shortly thereafter:

```
CMake Warning at src/CMakeLists.txt:44 (find_package):
  By not providing "FindPythonModuleGeneration.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "PythonModuleGeneration", but CMake did not find one.

  Could not find a package configuration file provided by
  "PythonModuleGeneration" with any of the following names:

    PythonModuleGenerationConfig.cmake
    pythonmodulegeneration-config.cmake

  Add the installation prefix of "PythonModuleGeneration" to
  CMAKE_PREFIX_PATH or set "PythonModuleGeneration_DIR" to a directory
  containing one of the above files.  If "PythonModuleGeneration" provides a
  separate development package or SDK, be sure it has been installed.
```

and then in the summary:

```
-- The following OPTIONAL packages have not been found:

 * PythonModuleGeneration
```

It was this that prompted me to specify these paths. But I realize now it's enough with just the:

```
"-DCMAKE_PREFIX_PATH=${CMAKE_BINARY_DIR}/prefix"
```

With that, I don't get a warning, and in the summary instead:

```
-- The following OPTIONAL packages have been found:

 * PythonModuleGeneration
...
```

But you're saying it doesn't make sense? Don't I need to tell CMake where to find `FindPythonModuleGeneration.cmake` since it's not in the directories searched by CMake by default? Or is `${CMAKE_BINARY_DIR}/prefix` the wrong directory to search at that point?

I gotto run off to work now, but can debug further when I'm home this evening.

**Comment by steveire** [comment]
> But you're saying it doesn't make sense? 

Correct. CMake has code for using the content of the `CMAKE_INSTALL_PREFIX` as a search prefix without having to duplicate it to `CMAKE_PREFIX_PATH`. Maybe your cmake version is old?

**Comment by estan** [comment]
Aha, didn't know it searched the install prefix. Then it's strange indeed. I'm on CMake 3.5.2 (Arch Linux).

**Comment by estan** [comment]
Hm, looking at the docs I can't find anything about searching `CMAKE_INSTALL_PREFIX` [1]. Could it be an undocumented behavior that was removed at some point? Should have been in the release note you would think though..

[1] https://cmake.org/cmake/help/v3.5/command/find_package.html

**Comment by steveire** [comment]
It is at least mentioned here: https://cmake.org/cmake/help/v3.5/variable/CMAKE_FIND_NO_INSTALL_PREFIX.html

You might construct a minimal testcase and report to the CMake mailing list if it doesn't work.

**Comment by estan** [comment]
Aha, yes, so it's part of `CMAKE_SYSTEM_PREFIX_PATH` I'll try to make a test case when I'm back home this afternoon.

**Pull request closed without merging**
